// In Vite config context, use process.env which is available at build time
// In runtime (app code), use import.meta.env
const ROOT_URL = process.env.VITE_BASE_URL || "http://localhost:3000";

export const minikitConfig = {
  accountAssociation: {
    header: "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4OTE1REEwQzJDMWY1NWFmOTc1ZDRCRjAzQzJkZEM3ODJDNzY1NDgyRiJ9",
    payload: "eyJkb21haW4iOiJsb2NhbGhvc3QifQ",
    signature: "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAARQDFg7v7iVu7FEnRXGq3ySfp5qoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAHRndW6wl9EYeukotJGrci4FQG-P4VsKjETsrUVlM9ARDq0s4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB3iKxNDzHJ4bNJZppqpK5I7rrdf9dVzhPw8wGXoze9-NiNySrTuggo6SlfkZcOLAp_VBvAoRy-EJc8lflbkcpyRwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI"
  },
  miniapp: {
    version: "1",
    name: "ScaleX",
    subtitle: "Cross-Chain Trading Platform",
    description: "A comprehensive cross-chain trading platform for seamless crypto trading, lending, and portfolio management.",
    screenshotUrls: [`${ROOT_URL}/docs-mockup.png`],
    iconUrl: `${ROOT_URL}/vite.svg`,
    splashImageUrl: `${ROOT_URL}/vite.svg`,
    splashBackgroundColor: "#000000",
    homeUrl: ROOT_URL,
    webhookUrl: `${ROOT_URL}/api/webhook`,
    primaryCategory: "finance",
    tags: ["trading", "defi", "crypto", "cross-chain"],
    heroImageUrl: `${ROOT_URL}/waitlist-page.png`,
    tagline: "Cross-Chain Trading Made Simple",
    ogTitle: "ScaleX - Cross-Chain Trading Platform",
    ogDescription: "Seamless cross-chain trading, lending, and portfolio management.",
    ogImageUrl: `${ROOT_URL}/waitlist-page.png`,
    noindex: false
  },
} as const;
